name: Build
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_LOGIN }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build and Push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ziolechka/flask-docker-swarm:latest
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Connect to Vagrant VM and deploy Docker Swarm stack
      run: |
         ssh -o StrictHostKeyChecking=no vagrant@7.tcp.eu.ngrok.io -p 13839 "cd /home/vagrant/docker_services_stacks/flask/ && docker stack deploy --compose-file compose.yaml stackdemo && sleep 60 && curl http://127.0.0.1:8000"
      shell: bash
